import Link from 'next/link';
import { Check, X, ArrowRight, Star, HelpCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';

export default function Pricing() {
  const pricingPlans = [
    {
      name: "Hobbyist",
      price: "Free",
      period: "Forever",
      description: "Perfect for learning and personal projects",
      features: [
        { name: "5 projects per month", included: true },
        { name: "Basic code generation", included: true },
        { name: "Community support", included: true },
        { name: "Standard MCU library", included: true },
        { name: "Basic firmware templates", included: true },
        { name: "Simple project examples", included: true },
        { name: "Advanced AI features", included: false },
        { name: "Priority support", included: false },
        { name: "Extended MCU library", included: false },
        { name: "Edge AI tools", included: false },
        { name: "FPGA workflows", included: false },
        { name: "Real-time BOM pricing", included: false },
        { name: "Custom integrations", included: false }
      ],
      popular: false,
      cta: "Get Started Free",
      ctaLink: "/signup"
    },
    {
      name: "Professional",
      price: "$29",
      period: "per month",
      description: "Ideal for professional developers and small teams",
      features: [
        { name: "Unlimited projects", included: true },
        { name: "Advanced AI code generation", included: true },
        { name: "Priority email support", included: true },
        { name: "Extended MCU library (100+)", included: true },
        { name: "Edge AI model compression", included: true },
        { name: "FPGA HDL generation", included: true },
        { name: "Real-time BOM pricing", included: true },
        { name: "Professional schematics", included: true },
        { name: "Code optimization", included: true },
        { name: "Advanced debugging tools", included: true },
        { name: "Export to popular IDEs", included: true },
        { name: "Custom integrations", included: false },
        { name: "On-premise deployment", included: false }
      ],
      popular: true,
      cta: "Start Professional",
      ctaLink: "/signup?plan=professional"
    },
    {
      name: "Enterprise",
      price: "Custom",
      period: "contact us",
      description: "For teams and organizations with advanced needs",
      features: [
        { name: "Everything in Professional", included: true },
        { name: "Unlimited team members", included: true },
        { name: "24/7 dedicated support", included: true },
        { name: "Custom MCU support", included: true },
        { name: "Advanced security features", included: true },
        { name: "Custom AI model training", included: true },
        { name: "On-premise deployment", included: true },
        { name: "Custom integrations", included: true },
        { name: "SLA guarantees", included: true },
        { name: "Training and onboarding", included: true },
        { name: "Account manager", included: true },
        { name: "Custom billing", included: true },
        { name: "Advanced analytics", included: true }
      ],
      popular: false,
      cta: "Contact Sales",
      ctaLink: "/contact"
    }
  ];

  const faq = [
    {
      question: "Can I switch plans anytime?",
      answer: "Yes, you can upgrade or downgrade your plan at any time. Changes take effect immediately and we'll prorate any billing differences."
    },
    {
      question: "What MCUs are supported?",
      answer: "We support 100+ microcontrollers including ESP32, STM32, Arduino, PIC, ARM Cortex-M series, and many more. The full list is available in our documentation."
    },
    {
      question: "Is there a free trial for paid plans?",
      answer: "Yes! All paid plans come with a 14-day free trial. No credit card required to start."
    },
    {
      question: "How does the AI code generation work?",
      answer: "Our AI models are trained on millions of electronics projects and component datasheets. Simply describe your project requirements and get production-ready firmware in minutes."
    },
    {
      question: "Do you offer educational discounts?",
      answer: "Yes, we offer 50% discounts for students and educational institutions. Contact us with your .edu email for verification."
    },
    {
      question: "Can I use generated code commercially?",
      answer: "Absolutely! All code generated by MCUZA is yours to use commercially without any licensing restrictions or royalties."
    }
  ];

  const comparisons = [
    {
      feature: "Monthly Projects",
      hobbyist: "5",
      professional: "Unlimited",
      enterprise: "Unlimited"
    },
    {
      feature: "MCU Support",
      hobbyist: "Basic (20+)",
      professional: "Extended (100+)",
      enterprise: "Full + Custom"
    },
    {
      feature: "AI Code Generation",
      hobbyist: "Basic",
      professional: "Advanced",
      enterprise: "Custom Models"
    },
    {
      feature: "Support",
      hobbyist: "Community",
      professional: "Priority Email",
      enterprise: "24/7 Dedicated"
    },
    {
      feature: "BOM Pricing",
      hobbyist: "Not included",
      professional: "Real-time",
      enterprise: "Real-time + Bulk"
    }
  ];

  return (
    <div className="flex flex-col min-h-screen bg-gray-950 text-white">
      {/* Hero Section */}
      <section className="relative py-20 px-4 bg-gradient-to-br from-gray-900 via-gray-800 to-gray-900">
        <div className="absolute inset-0 bg-gradient-to-r from-blue-600/20 to-cyan-600/20 opacity-30"></div>
        <div className="relative container mx-auto text-center max-w-4xl">
          <Badge className="mb-4 bg-gradient-to-r from-blue-600 to-cyan-600 text-white border-0">
            💰 Transparent Pricing
          </Badge>
          <h1 className="text-4xl md:text-6xl font-bold tracking-tight mb-6 text-white">
            Simple, Transparent
            <span className="bg-gradient-to-r from-blue-400 to-cyan-300 bg-clip-text text-transparent block">Pricing for Everyone</span>
          </h1>
          <p className="text-xl md:text-2xl text-gray-300 mb-8 max-w-3xl mx-auto leading-relaxed">
            Choose the perfect plan for your needs. Start free and upgrade as you grow. No hidden fees, no surprises.
          </p>
        </div>
      </section>

      {/* Pricing Cards */}
      <section className="py-20 px-4 bg-gray-900/30">
        <div className="container mx-auto max-w-7xl">
          <div className="grid lg:grid-cols-3 gap-8 items-start">
            {pricingPlans.map((plan, index) => (
              <Card key={index} className={`relative ${plan.popular ? 'border-2 border-blue-500 shadow-2xl scale-105 bg-gray-800/70' : 'border border-gray-700 bg-gray-800/50 shadow-lg'} transition-all hover:shadow-xl hover:shadow-blue-500/25 hover:bg-gray-800/70`}>
                {plan.popular && (
                  <div className="absolute -top-4 left-1/2 transform -translate-x-1/2">
                    <Badge className="bg-gradient-to-r from-blue-600 to-cyan-600 text-white px-4 py-1 border-0">
                      <Star className="w-3 h-3 mr-1" />
                      Most Popular
                    </Badge>
                  </div>
                )}
                
                <CardHeader className="text-center pb-6">
                  <CardTitle className="text-2xl font-bold text-white">{plan.name}</CardTitle>
                  <div className="mt-4">
                    <span className="text-4xl font-bold text-white">
                      {plan.price}
                    </span>
                    {plan.price !== 'Free' && plan.price !== 'Custom' && (
                      <span className="text-lg text-gray-400 ml-1">/{plan.period.split(' ')[1]}</span>
                    )}
                    <div className="text-sm text-gray-400 mt-1">
                      {plan.period}
                    </div>
                  </div>
                  <CardDescription className="mt-4 text-base text-gray-300">
                    {plan.description}
                  </CardDescription>
                </CardHeader>
                
                <CardContent className="space-y-6">
                  <div className="space-y-3">
                    {plan.features.map((feature, featureIndex) => (
                      <div key={featureIndex} className="flex items-center space-x-3">
                        {feature.included ? (
                          <Check className="h-4 w-4 text-green-400 flex-shrink-0" />
                        ) : (
                          <X className="h-4 w-4 text-gray-600 flex-shrink-0" />
                        )}
                        <span className={`text-sm ${!feature.included ? 'text-gray-600 line-through' : 'text-white'}`}>
                          {feature.name}
                        </span>
                      </div>
                    ))}
                  </div>
                  
                  <Button
                    className={`w-full mt-8 ${plan.popular ? 'bg-gradient-to-r from-blue-600 to-cyan-600 hover:from-blue-700 hover:to-cyan-700 border-0 shadow-lg' : 'border border-gray-600 text-white hover:bg-gray-700'}`}
                    size="lg"
                    asChild
                  >
                    <Link href={plan.ctaLink}>
                      {plan.cta}
                      <ArrowRight className="ml-2 h-4 w-4" />
                    </Link>
                  </Button>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Feature Comparison */}
      <section className="py-20 px-4 bg-gray-800/30">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold mb-4 text-white">
              Compare Plans in Detail
            </h2>
            <p className="text-xl text-gray-300">
              See exactly what's included in each plan
            </p>
          </div>
          
          <Card className="overflow-hidden border border-gray-700 bg-gray-800/50">
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="border-b border-gray-700">
                    <th className="text-left p-4 font-semibold text-white">Feature</th>
                    <th className="text-center p-4 font-semibold text-white">Hobbyist</th>
                    <th className="text-center p-4 font-semibold text-white bg-blue-500/10">
                      Professional
                      <Badge className="ml-2 bg-gradient-to-r from-blue-600 to-cyan-600 text-white border-0">Popular</Badge>
                    </th>
                    <th className="text-center p-4 font-semibold text-white">Enterprise</th>
                  </tr>
                </thead>
                <tbody>
                  {comparisons.map((comparison, index) => (
                    <tr key={index} className="border-b border-gray-700">
                      <td className="p-4 font-medium text-white">{comparison.feature}</td>
                      <td className="p-4 text-center text-gray-400">{comparison.hobbyist}</td>
                      <td className="p-4 text-center bg-blue-500/10 font-medium text-white">{comparison.professional}</td>
                      <td className="p-4 text-center text-gray-400">{comparison.enterprise}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </Card>
        </div>
      </section>

      {/* FAQ */}
      <section className="py-20 px-4 bg-gray-900/30">
        <div className="container mx-auto max-w-4xl">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold mb-4 text-white">
              Frequently Asked Questions
            </h2>
            <p className="text-xl text-gray-300">
              Everything you need to know about our pricing
            </p>
          </div>
          
          <div className="space-y-6">
            {faq.map((item, index) => (
              <Card key={index} className="p-6 border border-gray-700 bg-gray-800/50 hover:bg-gray-800/70 transition-all duration-300 hover:shadow-lg hover:shadow-blue-500/25">
                <div className="flex items-start space-x-4">
                  <HelpCircle className="h-5 w-5 text-blue-400 mt-1 flex-shrink-0" />
                  <div>
                    <h3 className="font-semibold text-lg mb-3 text-white">{item.question}</h3>
                    <p className="text-gray-300 leading-relaxed">{item.answer}</p>
                  </div>
                </div>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Enterprise CTA */}
      <section className="py-20 px-4 bg-gray-800/30">
        <div className="container mx-auto max-w-6xl">
          <Card className="p-8 text-center border border-gray-700 bg-gradient-to-br from-gray-800/80 to-gray-900/80">
            <CardHeader>
              <CardTitle className="text-3xl font-bold text-white">
                Need Something Custom?
              </CardTitle>
              <CardDescription className="text-xl mt-4 max-w-2xl mx-auto text-gray-300">
                Our Enterprise plan can be tailored to your specific needs. Volume discounts, custom features, and dedicated support available.
              </CardDescription>
            </CardHeader>
            <CardContent className="mt-6">
              <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
                <Button size="lg" className="bg-gradient-to-r from-blue-600 to-cyan-600 hover:from-blue-700 hover:to-cyan-700 border-0 shadow-lg" asChild>
                  <Link href="/contact">
                    Schedule a Demo
                    <ArrowRight className="ml-2 h-5 w-5" />
                  </Link>
                </Button>
                <Button size="lg" variant="outline" className="border border-gray-600 text-white hover:bg-gray-700" asChild>
                  <Link href="mailto:sales@mcuza.com">
                    Contact Sales Team
                  </Link>
                </Button>
              </div>
              <p className="text-sm text-gray-400 mt-4">
                Response within 24 hours • Custom quotes available
              </p>
            </CardContent>
          </Card>
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-20 px-4 bg-gradient-to-r from-blue-900 to-cyan-900 text-white">
        <div className="container mx-auto max-w-4xl text-center">
          <h2 className="text-3xl md:text-4xl font-bold mb-4 text-white">
            Ready to Get Started?
          </h2>
          <p className="text-xl mb-8 text-blue-100">
            Join thousands of developers who are building faster with MCUZA
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
            <Button size="lg" asChild className="text-lg px-8 py-6 bg-white text-blue-900 hover:bg-gray-100 border-0 shadow-lg">
              <Link href="/signup">
                Start Free Today
                <ArrowRight className="ml-2 h-5 w-5" />
              </Link>
            </Button>
            <Button size="lg" variant="outline" asChild className="text-lg px-8 py-6 border-white/30 text-white hover:bg-white/10 hover:border-white/50">
              <Link href="/rapid-prototyping">
                Try Rapid Prototyping
              </Link>
            </Button>
          </div>
          <p className="text-sm text-blue-200 mt-4">
            No credit card required • 14-day free trial • Cancel anytime
          </p>
        </div>
      </section>
    </div>
  );
}
